--- #YAML:1.0
name:               WebService-Antigate
version:            0.04
abstract:           Recognition of captches using antigate.com service (former anti-captcha.com)
author:
    - Oleg G <oleg@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  6.52
build_requires:
    Test::More:  0.88
requires:
    LWP::UserAgent:  0
resources:
    repository:  https://github.com/olegwtf/p5-WebService-Antigate
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
